name: CI

on:
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.prettierignore'
  push:
    branches: [dev, main]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.prettierignore'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ut:
    name: Unit Tests (Jest)
    runs-on: ubuntu-latest
    container:
      image:
        ghcr.io/slavamelanko/smela-front-ci:${{ (github.event_name ==
        'pull_request' && github.base_ref) || github.ref_name }}
    environment: test
    env:
      HUSKY: 0
      VITE_CAPTCHA_SITE_KEY: ${{ secrets.VITE_CAPTCHA_SITE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run ut:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
