name: CI

on:
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.prettierignore'
  push:
    branches: [dev, main]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.prettierignore'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  ut:
    name: Unit Tests (Jest)
    runs-on: ubuntu-latest
    container:
      image:
        ghcr.io/slavamelanko/smela-front-ci:${{ (github.event_name ==
        'pull_request' && github.base_ref) || github.ref_name }}
    environment: test
    env:
      VITE_CAPTCHA_SITE_KEY: ${{ secrets.VITE_CAPTCHA_SITE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run ut:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  bundle-stats:
    name: Bundle Analysis (RelativeCI)
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: test
    container:
      image: ghcr.io/slavamelanko/smela-front-ci:dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build and generate bundle stats
        run: npm run bundle:analyze

      - name: Upload bundle visualizer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-visualizer
          path: dist/bundle-visualizer.html
          retention-days: 90

      - name: Upload bundle stats to RelativeCI
        uses: relative-ci/agent-action@v3
        with:
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          webpackStatsFile: ./dist/webpack-stats.json
